### ISSUE TITLE
doesnt repeat correct recording

### ISSUE THREAD

**Issue by warclonex** [LOUDO56/PyMacroRecord#10]
using it within a game

after recording the maco seems to be only doing the first action

ie if i record myself pressing the 'W' key then [any key after that] it will only press the W once even if i have it on repeat

**Comment by warclonex** [comment]
after some tinkering and resetting all options i seem to have gotten it to play the sequence once only and will not repeat

**Comment by LOUDO56** [comment]
Hello, can you provide me the record file? Thanks

**Comment by warclonex** [comment]
sorry im completely new at all this... where/how would i do that

I also tried simply leaving the repeat option as 1 but after one run its seems the be "stuck" on play ie the square stop button is still up ( i would resume it would reset and the play button be presented?)

**Comment by LOUDO56** [comment]
It means the record crashes the software. I need to put a box when there's a error.

In the software save it on your PC and open the file of your record on a notepad, then copy all the stuff in the file and paste it there.
Be sure to put that in a code box 

```
Like this
```

**Comment by warclonex** [comment]
{
    "events": [
        {
            "type": "keyboardEvent",
            "key": "w",
            "timestamp": 2.3089206218719482,
            "pressed": true
        },
        {
            "type": "keyboardEvent",
            "key": "w",
            "timestamp": 0.1337578296661377,
            "pressed": false
        },
        {
            "type": "keyboardEvent",
            "key": "Key.enter",
            "timestamp": 0.018949508666992188,
            "pressed": true
        },
        {
            "type": "keyboardEvent",
            "key": "Key.enter",
            "timestamp": 0.09874820709228516,
            "pressed": false
        },
        {
            "type": "keyboardEvent",
            "key": "Key.f6",
            "timestamp": 0.6169168949127197,
            "pressed": true
        }
    ]
}

**Comment by LOUDO56** [comment]
Thanks, I'm looking into it, I'll update it today. Sorry for the inconvenience.

**Comment by warclonex** [comment]
great appears to be working fine now appreciate it!
