### ISSUE TITLE
no internet leads to crash

### ISSUE THREAD

**Issue by tobwen** [LOUDO56/PyMacroRecord#12]
**Describe the bug**
When you start the portable application, a connection to api.github.com (and perhaps also to other services) is established. If no internet is available, the application crashes.

**To Reproduce**
Turn off network or turn on more aggressive firefall.

**Screenshots**
![image](https://github.com/LOUDO56/PyMacroRecord/assets/1864057/4b90732b-856c-48d5-958a-9dd16d373271)

**The OS**
Windows 10, 64-bit, Version 10.0.19045.3930

**Additional context**
It is unexpected that a portable application requires an internet connection by default. It also doesn't seem very trustworthy.

**Update**
Seems to be an unexpected  version check with uncaught exception:
https://github.com/LOUDO56/PyMacroRecord/blob/b54c42313c13de64566881a2ee9e0be1ae0fc731/src/utils/version.py#L13

**Comment by LOUDO56** [comment]
Hello, I only use internet to check if the software has a new version available by checking it in the github api. It is possible to disable it in the settings if you wish, check [tutorial](https://github.com/LOUDO56/PyMacroRecord/blob/main/TUTORIAL.md#others).

This problem has been fixed, check [v1.1.11](https://github.com/LOUDO56/PyMacroRecord/releases/tag/v1.1.11)
