### ISSUE TITLE
I moved the portable exe to another folder, the program wont launch and it gives me an error

### ISSUE THREAD

**Issue by grannymaster** [LOUDO56/PyMacroRecord#17]
**Describe the bug**
I moved the portable exe to another folder, the program wont launch and it gives me this error:
![image](https://github.com/LOUDO56/PyMacroRecord/assets/79359055/de6b86b6-fd92-4613-aa49-706a86288216)

**To Reproduce**
Double click the .exe

**The OS**
W11 23H2
**Additional context**
I deleted the userconfig.json from appdata, rebooted PC, didn't help.

**Comment by LOUDO56** [comment]
Hello, I don't think this problem comes from the software but from your Windows.
Try to launch the software as administrator mode.

**Comment by grannymaster** [comment]
Ah I see. My AV flagged it.

**Comment by LOUDO56** [comment]
Of course. I can't really deal with that since I compile my code with Pyinstaller and all I can do is to submit for false positive. Sorry for the inconveniences
