### ISSUE TITLE
MacOS Crash on record

### ISSUE THREAD

**Issue by orn8** [LOUDO56/PyMacroRecord#23]
**Describe the bug**
When I tried to record a macro, the app instantly crashes.
The terminal just says: `zsh: trace trap  python3 main.py`

**To Reproduce**
Click the record button on the app.

**Screenshots**

https://github.com/LOUDO56/PyMacroRecord/assets/119661802/6cbdc2e3-112a-48c6-b46a-13b13c4ebc8b

<img width="604" alt="Screenshot 2024-05-22 at 3 01 58 PM" src="https://github.com/LOUDO56/PyMacroRecord/assets/119661802/32265cf0-40d6-49f6-a7a9-1915b40cb36d">

**The OS**
MacOS

**Additional context**
I have already given accessibility and input monitoring permissions to both terminal and the python app.

**Comment by LOUDO56** [comment]
Hello, can you try loading a script and playt it to see if it does the same?
[test-macos.json](https://github.com/LOUDO56/PyMacroRecord/files/15418396/test-macos.json)

**Comment by orn8** [comment]
Yeah that works fine. I guess it's just the recording that's causing the error.

https://github.com/LOUDO56/PyMacroRecord/assets/119661802/30f4a0ef-a003-47af-8aee-d6ae27e06fd5

**Comment by LOUDO56** [comment]
That's a good start, now can you try to record only the mouse movement, keyboard input and mouse click to see if one in particular cause the crash please?

**Comment by orn8** [comment]
It seems to only crash when enabling recording of keyboard strokes. Mouse movement and clicks are working.

**Comment by LOUDO56** [comment]
Nice. Lastly, can you test this macro script that use keyboard input? 
[test-keyboard.json](https://github.com/LOUDO56/PyMacroRecord/files/15429403/test-keyboard.json)

**Comment by orn8** [comment]
Yup the keyboard macro is working. It's just the recording that's causing the error.

**Comment by LOUDO56** [comment]
It's avalaible. If you used git to download PMR, just use `git pull` or else download the source code from the lastest release https://github.com/LOUDO56/PyMacroRecord/releases/tag/V1.1.6
