### ISSUE TITLE
playback menu

### ISSUE THREAD

**Issue by szecsip-szecsi** [LOUDO56/PyMacroRecord#26]
I’m using the program on Windows. The save option is not visible in the playback-for setting and playback -  interval setting windows, so the set values cannot be saved. The displayed window is probably too small in size.
<img width="356" alt="Jegyzet 2024-07-05 134305" src="https://github.com/LOUDO56/PyMacroRecord/assets/134429616/06a9147b-02a3-4d22-8e09-f1fccad90296">

**Comment by LOUDO56** [comment]
Hi, what's your screen resolution?

**Comment by szecsip-szecsi** [comment]
1920x1080, and I've tried lower resolutions too.

LOUDO ***@***.***> ezt írta (időpont: 2024. júl. 5., Pén
20:49):

**Comment by DopamineUser** [comment]
same issue, i use 150% zoom
