### ISSUE TITLE
Scheduled start

### ISSUE THREAD

**Issue by szecsip-szecsi** [LOUDO56/PyMacroRecord#27]
I use the program to record reservations on a site where you can only book at a certain time each day. It would be useful to have a function in the program that starts the previously recorded macro at a preset time (hh:mm:ss)

**Comment by LOUDO56** [comment]
Good Idea, I will do that when I'll have some time.

**Comment by szecsip-szecsi** [comment]
Hi, that's great!

LOUDO ***@***.***> ezt írta (időpont: 2024. júl. 5., Pén
20:50):
