### ISSUE TITLE
Language: Chinese

### ISSUE THREAD

**Issue by DennyClarkson** [LOUDO56/PyMacroRecord#29]
zh-CN language. First time using Github so..I do not know how to make a pull request. Translated it here.
[zh-CN.json](https://github.com/user-attachments/files/16137288/zh-CN.json)

**Comment by DennyClarkson** [comment]
plz forgive me if I did anything wrong

**Comment by LOUDO56** [comment]
Ohh that's really cool! But I suggest you to do that instead, first fork my code.
![image](https://github.com/LOUDO56/PyMacroRecord/assets/117168736/a5ac68fa-082a-4686-8be6-9710138d7427)
Then, go in `src/langs`, click add fille and upload file
![image](https://github.com/LOUDO56/PyMacroRecord/assets/117168736/7a386b52-8fcb-40d4-b274-d8e69c1293b5)
Finally, go back to the main page of your fork, and and click on contribute
![image](https://github.com/LOUDO56/PyMacroRecord/assets/117168736/01e4628b-6aef-4242-b771-b6d813bad5e8)
It will create a pull request, that I will merge, and you will appear as a contributor on my main page of PyMacroRecord :)

**Comment by DennyClarkson** [comment]
Huge thanks! I have created a pull request successfully, thank you for the guide. This recorder is awesome, it is the best and the simplist recorder I've ever used.
