### ISSUE TITLE
Mac os Support

### ISSUE THREAD

**Issue by ahmetinal46** [LOUDO56/PyMacroRecord#3]
Can you update new version mac os support i try some changes but not work and 
2023-11-01 09:03:58.713 Python[11502:224062] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], NSUndoManager.m:1117 error

**Comment by LOUDO56** [comment]
Hello, I have updated PyMacroRecord and his [tutorial](https://www.pymacrorecord.com/download#installation-not-windows) to use it on Mac or Linux.
I cannot test it on Mac OS unfortunately, but this should work.
Remember that you need Python to run it.
