### ISSUE TITLE
Multiple hotkeys and records? Like GHUB?

### ISSUE THREAD

**Issue by DennyClarkson** [LOUDO56/PyMacroRecord#31]
I've noticed that I can open multiple PyMacroRecord windows, and I can load different .pmr files in different windows. However they all share the same setting (hotkeys, intervals, etc.). Is that possible to have multiples settings (or presets) and the users could choose before entering the main page?
Or just create a new temporate setting when a new window is opened?
![image](https://github.com/LOUDO56/PyMacroRecord/assets/175077879/7882c2c2-86a2-40a6-9084-3ce17c3a4091)

**Comment by LOUDO56** [comment]
Well, After thinking it can be useful but it's better if the settings are in the macro file itself, rather than presets
