### ISSUE TITLE
Load & run multiple recorded files in desired sequence.

### ISSUE THREAD

**Issue by jkjayankumar** [LOUDO56/PyMacroRecord#33]
Thanks for the Software.
I just made a donation Ko-fi.
Pasting my request from there below :
Please add functionality to load & run multiple recorded files in desired sequence.
With seperate indivisual playback repeat setting for each.

Example = Playback (file1) X 3 times +
play (file2) X 2 times + play (file3) x 5 times + play (file1) X 2 times

**Comment by LOUDO56** [comment]
It will be a bit tricky but I'll see what I can do
