### ISSUE TITLE
Optimize Option for .PMR files

### ISSUE THREAD

**Issue by hl2guide** [LOUDO56/PyMacroRecord#34]
**Is your feature request related to a problem? Please describe.**
PMR files record specific movements of the mouse and as a result they less legible than they should be.

**Describe the solution you'd like**
The ability to optimize PMR files would be useful for scripts that still work without an exact mouse path/movement. Avoiding the output of over 200KB PMR files for simple recordings.

e.g.

```
move mouse pointer to 200,300
Click left mouse button
wait 2 seconds
end
```

thanks for making useful software.

**Comment by LOUDO56** [comment]
Hello, yes I'll have to take a look at it, but for now if you want, you can record macros without the mouse movement and only recording the clicks.
