### ISSUE TITLE
display of interface 

### ISSUE THREAD

**Issue by student533** [LOUDO56/PyMacroRecord#37]
**Describe the bug**
i found a bug that applies on peculiar display resolution (like mine).

**To Reproduce**
set your pc to have a display resolution to 3840 x 2400
then open the app

**Screenshots**
![Capture 1](https://github.com/user-attachments/assets/dc7ee2e5-870c-4c2f-8afb-336c5d3d16e4)
![Capture 2](https://github.com/user-attachments/assets/12489323-3f7f-4fe7-9fc2-85bdce360bea)

**The OS**
![Capture 3](https://github.com/user-attachments/assets/9a965206-139d-49a7-827d-48c39bee2f1a)

**Additional context**
i believe the reason why there's a bug is because Windows tries to scale everything about the app (see 3rd screenshot).
while the interface of the application is messed up, everything function the way it should. no problem on that.

**Comment by student533** [comment]
**Found a way to resolve the bug**
i don't know if we can recode part of the app to fix the bug by itself or not.
what do you all think?

**To Reproduce**
-Right-click on the desktop shortcut of the app.
-Select Properties.
-Go to the Compatibility tab.

then 
-Select Change high DPI settings
![Capture 4](https://github.com/user-attachments/assets/666d1233-18a6-41db-996c-9d067626e205)

-Select the second square
-Choose the scaling to be performed by "System"
![Capture 5](https://github.com/user-attachments/assets/f446de9c-bc8d-488a-bf4d-fb8336283b5c)

**Comment by LOUDO56** [comment]
The problem with higher resolution is that it breaks the coordinates of your mouse on the record, it's probably a issue of Pynput and I can't really do much about it. The only solution someone suggested is to enable high DPI to resolve this issue, but it creates that weird tiny interface. So... It's a bit complicated.
