### ISSUE TITLE
Playback '\\' meet error

### ISSUE THREAD

**Issue by lihong-roy** [LOUDO56/PyMacroRecord#42]
<img width="393" alt="playback_error" src="https://github.com/user-attachments/assets/e0cf2f87-6330-48e6-b075-66d38390b037">

**Comment by LOUDO56** [comment]
Hi, can you share the macro file ? Thanks

**Comment by lihong-roy** [comment]
Hi, I 've uploaded the file, please check, Thanks.
[error_file.zip](https://github.com/user-attachments/files/17100047/error_file.zip)
