### ISSUE TITLE
Repeat on condition

### ISSUE THREAD

**Issue by FuzzyLotus** [LOUDO56/PyMacroRecord#44]
Presently trying to automate a task,
I'd love to set the PyMacroRecord to run through the macro, then automatically start again when a tab becomes active, or when part of a window becomes visible or when a certain keystroke sequence is detected.

Why? 

Basically I have set up another script that runs through a manual task, grabs info from an excel sheet on o365, pastes it in another chrome tab and does it's function, then ends by returning to the o365 tab and writes "done" in a cell.

Presently I've set it to repeat using intervals but I'd feel it would run much quicker and smoother if it repeated when the word done is being input instead of just having it wait a few seconds before starting again.  To make it less of a niche request, instead of when keystroke is detected function, it could just be when a tab or something becomes active, that way more people could use this function :P

Cheers!

**Comment by LOUDO56** [comment]
Hi, unfortunately it's a bit too tricky and I want to leave PyMacroRecord a nice and simple macro software, there's more complex MacroRecorder that can fit your needs like AutoHotKey or Pulover's Macro Creator.
