### ISSUE TITLE
Enhancement: Fixed timestamp playback

### ISSUE THREAD

**Issue by Auburn** [LOUDO56/PyMacroRecord#9]
Hi this tool is great!
The one feature I would like is to playback a recording at near instantaneous speed.
I can currently emulate this by saving a recording and editing the json so that every timestamp is very short like so `"timestamp": 0.01` 
But it would be great to have a setting in the UI for fixed timestamp playback speed, so I don't need to edit the json

Thanks!

**Comment by LOUDO56** [comment]
Hello, you can change the speed value to 0.1 or lower if you want to have the same result, check [tutorial](https://github.com/LOUDO56/PyMacroRecord/blob/main/TUTORIAL.md#speed).

**Comment by Auburn** [comment]
I'm already running it with a value of 10, manually changing the timestamps in the json is still much quicker. The problem other with scaling that high is that then some keypresses will have such a short timestamps that the input gets skipped by the application. Having fixed timestamps avoids this issue

**Comment by LOUDO56** [comment]
Yeah i just understood the request. I noted it.

**Comment by LOUDO56** [comment]
Hello, your request has been added. Check [v1.1.1](https://github.com/LOUDO56/PyMacroRecord/releases/tag/v1.1.1)

**Comment by LOUDO56** [comment]
Feature removed in [v1.4.4](https://github.com/LOUDO56/PyMacroRecord/releases/tag/v1.4.4)
